# Generated by Django 4.0.3 on 2022-03-22 11:22

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, validators=[common.validators.validate_only_letters])),
                ('last_name', models.CharField(max_length=25, validators=[common.validators.validate_only_letters])),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
            ],
        ),
    ]
